#!/usr/bin/env bash

if ! command -v cargo-binstall &> /dev/null; then
    echo "Installing cargo-binstall..."
    curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
fi

if ! command -v cargo-make &> /dev/null; then
    echo "Installing cargo-make..."
    cargo binstall cargo-make
fi

if [ $# -eq 0 ] || [ "$1" = "-h" ] || [ "$1" =  "--help" ]; then
    cargo make --list-all-steps --hide-uninteresting
    exit 0
fi

cargo make "$@"
