[config]
default_to_workspace = false
# Skip loading of all core tasks which saves up a bit on toml parsing and task creation
skip_core_tasks = true
# Skips loading Git related environment variables
skip_git_env_info = true
# Skips loading rust related environment variables
skip_rust_env_info = true
# Skips loading the current crate related environment variables
skip_crate_env_info = true
min_version = "0.36.10"

[tasks.install-nextest]
category = "Misc"
description = "install cargo-nextest"
install_crate = { crate_name = "cargo-nextest", version = "0.9.133", binary = "cargo", test_arg = [
    "nextest",
    "--help",
] }

[tasks.install-llvm-cov]
category = "Misc"
description = "install cargo-llvm-cov"
install_crate = { crate_name = "cargo-llvm-cov", version = "0.8.6", binary = "cargo", test_arg = [
    "llvm-cov",
    "--help",
] }

[tasks.clean]
category = "Dev - check"
description = "Run cargo clean"
command = "cargo"
args = ["clean"]

[tasks.check-clippy]
category = "Dev - check"
description = "Run full cargo clippy check"
script = """
#!/usr/bin/env bash

cargo clippy --all-features --all-targets -- -D warnings
"""

[tasks.check-fmt]
category = "Dev - check"
description = "Run cargo fmt check"
command = "cargo"
args = ["fmt", "--all"]

[tasks.check-typos]
category = "Dev - check"
description = "Run cargo typos-cli check"
install_crate = { version = "1.46.1", crate_name = "typos-cli", binary = "typos", test_arg = [
    "--help",
] }
script = """
#!/usr/bin/env bash
set -e

typos || { echo "Hint: use 'typos -w' to fix."; exit 1; }
echo "typos check pass !"
"""

[tasks.check-machete]
category = "Dev - check"
description = "Run cargo machete check"
install_crate = { version = "0.9.2", crate_name = "cargo-machete", binary = "cargo", test_arg = [
    "machete",
    "--help",
] }
script = """
#!/usr/bin/env bash
set -e

cargo machete
"""

[tasks.test-cov]
category = "Dev - check"
description = "Run unit tests and report coverage"
dependencies = ["install-llvm-cov", "install-nextest"]
script = """
#!/usr/bin/env bash
set -e

cargo llvm-cov nextest --all-features --all-targets --html
"""

[tasks.test]
category = "Dev - check"
description = "Run unit tests"
dependencies = ["install-nextest"]
script = """
#!/usr/bin/env bash
set -e

cargo nextest run --all-features --all-targets
"""

[tasks.check]
category = "Dev - check"
description = "Run all checks one by one"
dependencies = [
    "check-fmt",
    "check-clippy",
    "check-machete",
    "test",
    "check-typos",
]
